{% set name = "codem" %}
{% set version = "0.25.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/codem-{{ version }}.tar.gz
  sha256: 3c88e5ea57bc0fb9ec4ef2010f8919d106be06577c1c4d160f3729a419419b78

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - codem = codem.main:main
    - vcd = vcd.main:main

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=64.0
  run:
    - python >=3.9
    - typing-extensions
    - numpy
    - {{ pin_compatible('python-pdal', max_pin='x.x.x') }}
    - opencv
    - rasterio
    - trimesh
    - matplotlib-base
    - scikit-image
    - rich
    - pyproj
    - pyshp
    - pandas
    - scipy
    - pyyaml

test:
  imports:
    - codem
    - vcd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NCALM-UH/CODEM
  summary: A package for co-registering geospatial data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - j9ac9k
    - hobu
    - chambbj
