{% set name = "codem" %}
{% set version = "0.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/codem-{{ version }}.tar.gz
  sha256: bef6238dca68c0829b85c025420b048086a1830672e51d8a13647687cef9f273

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - codem = codem.main:main
    - vcd = vcd.main:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64.0
  run:
    - python >={{ python_min }}
    - typing-extensions
    - numpy
    - {{ pin_compatible('python-pdal', max_pin='x.x.x') }}
    - opencv
    - rasterio
    - trimesh
    - matplotlib-base
    - scikit-image
    - rich
    - pyproj
    - pyshp
    - pandas
    - scipy
    - pyyaml
    - mesalib

test:
  imports:
    - codem
    - vcd
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/NCALM-UH/CODEM
  summary: A package for co-registering geospatial data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - j9ac9k
    - hobu
    - chambbj
